<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        // ล้างข้อมูลเก่าก่อน ป้องกัน id ซ้ำ
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('ems_employees')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('ems_employees')->insert([
            // ===================== MANAGEMENT =====================
            [
                'id' => 1,
                'emp_id' => 'CN000',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'สมชัย',
                'emp_lastname' => 'ผู้บริหาร',
                'emp_nickname' => 'Admin',
                'emp_email' => 'admin@company.com',
                'emp_phone' => '0891234567',
                'emp_department_id' => 8,
                'emp_team_id' => 12,
                'emp_position_id' => 28,
                'emp_password' => Hash::make('Admin_Pass101'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => null,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 2,
                'emp_id' => 'CN001',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาง',
                'emp_firstname' => 'ธิดา',
                'emp_lastname' => 'บัณฑิต',
                'emp_nickname' => 'Tida',
                'emp_email' => 'tida.hr@company.com',
                'emp_phone' => '0892345678',
                'emp_department_id' => 20,
                'emp_team_id' => 41,
                'emp_position_id' => 71,
                'emp_password' => Hash::make('HR_Pass909'),
                'emp_permission' => 'hr',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== ARTIFICIAL INTELLIGENCE =====================
            [
                'id' => 3,
                'emp_id' => 'CN002',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'วิศวัส',
                'emp_lastname' => 'เทพากร',
                'emp_nickname' => 'Wise',
                'emp_email' => 'viswat.ai@company.com',
                'emp_phone' => '0893456789',
                'emp_department_id' => 1,
                'emp_team_id' => 1,
                'emp_position_id' => 1,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 4,
                'emp_id' => 'CN003',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'นัทชา',
                'emp_lastname' => 'ศิลปกุล',
                'emp_nickname' => 'Nat',
                'emp_email' => 'natcha.ml@company.com',
                'emp_phone' => '0894567890',
                'emp_department_id' => 1,
                'emp_team_id' => 1,
                'emp_position_id' => 2,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== CHATCONE DEVELOPMENT =====================
            [
                'id' => 5,
                'emp_id' => 'CN004',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ธนพงษ์',
                'emp_lastname' => 'ชื่นชม',
                'emp_nickname' => 'Thon',
                'emp_email' => 'thon.fullstack@company.com',
                'emp_phone' => '0895678901',
                'emp_department_id' => 2,
                'emp_team_id' => 2,
                'emp_position_id' => 9,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 6,
                'emp_id' => 'CN005',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'ปรีญา',
                'emp_lastname' => 'สุขะวัฒน์',
                'emp_nickname' => 'Pree',
                'emp_email' => 'preeya.ba@company.com',
                'emp_phone' => '0896789012',
                'emp_department_id' => 2,
                'emp_team_id' => 2,
                'emp_position_id' => 8,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 7,
                'emp_id' => 'CN006',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ปิยะ',
                'emp_lastname' => 'จันทร์นี',
                'emp_nickname' => 'Piyu',
                'emp_email' => 'piya.support@company.com',
                'emp_phone' => '0897890123',
                'emp_department_id' => 2,
                'emp_team_id' => 3,
                'emp_position_id' => 12,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== DEVELOPER TEAM =====================
            [
                'id' => 8,
                'emp_id' => 'CN007',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ศัฐพล',
                'emp_lastname' => 'วัฒนากร',
                'emp_nickname' => 'Sot',
                'emp_email' => 'sathapol.dev@company.com',
                'emp_phone' => '0898901234',
                'emp_department_id' => 3,
                'emp_team_id' => 4,
                'emp_position_id' => 14,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 9,
                'emp_id' => 'CN008',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'อรไท',
                'emp_lastname' => 'สุวรรณศรี',
                'emp_nickname' => 'Ate',
                'emp_email' => 'oratai.dev@company.com',
                'emp_phone' => '0899012345',
                'emp_department_id' => 3,
                'emp_team_id' => 4,
                'emp_position_id' => 14,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== GRAPHIC DESIGN =====================
            [
                'id' => 10,
                'emp_id' => 'CN009',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'กันต์',
                'emp_lastname' => 'สินธุมา',
                'emp_nickname' => 'Kun',
                'emp_email' => 'kan.designer@company.com',
                'emp_phone' => '0890123456',
                'emp_department_id' => 4,
                'emp_team_id' => 5,
                'emp_position_id' => 16,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 11,
                'emp_id' => 'CN010',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'จิณณ์',
                'emp_lastname' => 'สุขสำรัญ',
                'emp_nickname' => 'Jin',
                'emp_email' => 'jin.ui@company.com',
                'emp_phone' => '0891234567',
                'emp_department_id' => 4,
                'emp_team_id' => 5,
                'emp_position_id' => 18,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== IT SUPPORT =====================
            [
                'id' => 12,
                'emp_id' => 'CN011',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'เสกสรรค์',
                'emp_lastname' => 'เดชคุณ',
                'emp_nickname' => 'Sek',
                'emp_email' => 'seksak.it@company.com',
                'emp_phone' => '0892345678',
                'emp_department_id' => 5,
                'emp_team_id' => 6,
                'emp_position_id' => 20,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== QUALITY ASSURANCE =====================
            [
                'id' => 13,
                'emp_id' => 'CN012',
                'emp_company_id' => 1,
                'emp_prefix' => 'นายหญิง',
                'emp_firstname' => 'นวลทิพย์',
                'emp_lastname' => 'สิทธิประสิทธิ์',
                'emp_nickname' => 'Nual',
                'emp_email' => 'nual.qa@company.com',
                'emp_phone' => '0893456789',
                'emp_department_id' => 9,
                'emp_team_id' => 17,
                'emp_position_id' => 21,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== SALES =====================
            [
                'id' => 14,
                'emp_id' => 'CN013',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'วรชัย',
                'emp_lastname' => 'งามเนตร',
                'emp_nickname' => 'War',
                'emp_email' => 'watchai.sales@company.com',
                'emp_phone' => '0894567890',
                'emp_department_id' => 10,
                'emp_team_id' => 18,
                'emp_position_id' => 28,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== MOBILE DEVELOPMENT =====================
            [
                'id' => 15,
                'emp_id' => 'CN014',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ชัยพร',
                'emp_lastname' => 'ศรีสวัสดิ์',
                'emp_nickname' => 'Chai',
                'emp_email' => 'chaiporn.mobile@company.com',
                'emp_phone' => '0895678901',
                'emp_department_id' => 9,
                'emp_team_id' => 15,
                'emp_position_id' => 14,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== ACCOUNTING =====================
            [
                'id' => 16,
                'emp_id' => 'CN015',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาง',
                'emp_firstname' => 'วันดี',
                'emp_lastname' => 'การเงิน',
                'emp_nickname' => 'Wan',
                'emp_email' => 'wan.accounting@company.com',
                'emp_phone' => '0896789012',
                'emp_department_id' => 8,
                'emp_team_id' => 11,
                'emp_position_id' => 28,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== SYSTEM ENGINEER =====================
            [
                'id' => 17,
                'emp_id' => 'CN016',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'บรรจง',
                'emp_lastname' => 'ปรัชญานันต์',
                'emp_nickname' => 'Ban',
                'emp_email' => 'banjong.devops@company.com',
                'emp_phone' => '0897890123',
                'emp_department_id' => 13,
                'emp_team_id' => 27,
                'emp_position_id' => 24,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== CLOUD INFRASTRUCTURE =====================
            [
                'id' => 18,
                'emp_id' => 'CN017',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'นครินทร์',
                'emp_lastname' => 'ศรีสวรรค์',
                'emp_nickname' => 'Nak',
                'emp_email' => 'nakorin.cloud@company.com',
                'emp_phone' => '0898901234',
                'emp_department_id' => 16,
                'emp_team_id' => 30,
                'emp_position_id' => 53,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 19,
                'emp_id' => 'CN018',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'อรุณ',
                'emp_lastname' => 'ฟ้องฟ้อง',
                'emp_nickname' => 'Arun',
                'emp_email' => 'arun.ops@company.com',
                'emp_phone' => '0899012345',
                'emp_department_id' => 16,
                'emp_team_id' => 31,
                'emp_position_id' => 55,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== DATA ANALYTICS =====================
            [
                'id' => 20,
                'emp_id' => 'CN019',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'ศรีบูล',
                'emp_lastname' => 'บัวโคท',
                'emp_nickname' => 'Sri',
                'emp_email' => 'sribul.bi@company.com',
                'emp_phone' => '0890123456',
                'emp_department_id' => 17,
                'emp_team_id' => 32,
                'emp_position_id' => 57,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 21,
                'emp_id' => 'CN020',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ประชิต',
                'emp_lastname' => 'เก่งหนัก',
                'emp_nickname' => 'Pra',
                'emp_email' => 'prachit.data@company.com',
                'emp_phone' => '0891234567',
                'emp_department_id' => 17,
                'emp_team_id' => 33,
                'emp_position_id' => 59,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 22,
                'emp_id' => 'CN021',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'พิมพ์พา',
                'emp_lastname' => 'มาสได',
                'emp_nickname' => 'Pimpa',
                'emp_email' => 'pimpa.analytics@company.com',
                'emp_phone' => '0892345678',
                'emp_department_id' => 17,
                'emp_team_id' => 34,
                'emp_position_id' => 61,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== CUSTOMER SUCCESS =====================
            [
                'id' => 23,
                'emp_id' => 'CN022',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'สมพร',
                'emp_lastname' => 'ใจดี',
                'emp_nickname' => 'Som',
                'emp_email' => 'somporn.support@company.com',
                'emp_phone' => '0893456789',
                'emp_department_id' => 18,
                'emp_team_id' => 35,
                'emp_position_id' => 63,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 24,
                'emp_id' => 'CN023',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'มนัสนัน',
                'emp_lastname' => 'ประสาทพร',
                'emp_nickname' => 'Mana',
                'emp_email' => 'manasunan.impl@company.com',
                'emp_phone' => '0894567890',
                'emp_department_id' => 18,
                'emp_team_id' => 36,
                'emp_position_id' => 65,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 25,
                'emp_id' => 'CN024',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'สัญชัย',
                'emp_lastname' => 'สุขสกาล',
                'emp_nickname' => 'Chai',
                'emp_email' => 'sanchai.csm@company.com',
                'emp_phone' => '0895678901',
                'emp_department_id' => 18,
                'emp_team_id' => 37,
                'emp_position_id' => 67,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== MARKETING & BRAND =====================
            [
                'id' => 26,
                'emp_id' => 'CN025',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'ชนมเลศ',
                'emp_lastname' => 'บรรพยัส',
                'emp_nickname' => 'Chon',
                'emp_email' => 'chon.brand@company.com',
                'emp_phone' => '0896789012',
                'emp_department_id' => 19,
                'emp_team_id' => 38,
                'emp_position_id' => 69,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 27,
                'emp_id' => 'CN026',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ชาญ',
                'emp_lastname' => 'บรรวอง',
                'emp_nickname' => 'Charn',
                'emp_email' => 'charn.marketing@company.com',
                'emp_phone' => '0897890123',
                'emp_department_id' => 19,
                'emp_team_id' => 39,
                'emp_position_id' => 71,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 28,
                'emp_id' => 'CN027',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'ธัญพร',
                'emp_lastname' => 'กตินช',
                'emp_nickname' => 'Tan',
                'emp_email' => 'thanporn.content@company.com',
                'emp_phone' => '0898901234',
                'emp_department_id' => 19,
                'emp_team_id' => 40,
                'emp_position_id' => 73,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== HR & LEARNING =====================
            [
                'id' => 29,
                'emp_id' => 'CN028',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'นวลจันทร์',
                'emp_lastname' => 'บัวคำ',
                'emp_nickname' => 'Noi',
                'emp_email' => 'noi.recruit@company.com',
                'emp_phone' => '0899012345',
                'emp_department_id' => 20,
                'emp_team_id' => 42,
                'emp_position_id' => 75,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 30,
                'emp_id' => 'CN029',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'อนันต์',
                'emp_lastname' => 'กิตติมัง',
                'emp_nickname' => 'Nan',
                'emp_email' => 'anon.learning@company.com',
                'emp_phone' => '0890123457',
                'emp_department_id' => 20,
                'emp_team_id' => 43,
                'emp_position_id' => 79,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== LEGAL & COMPLIANCE =====================
            [
                'id' => 31,
                'emp_id' => 'CN030',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'สุรศักดิ์',
                'emp_lastname' => 'สายสวรรค์',
                'emp_nickname' => 'Surasak',
                'emp_email' => 'surasak.legal@company.com',
                'emp_phone' => '0891234568',
                'emp_department_id' => 21,
                'emp_team_id' => 44,
                'emp_position_id' => 81,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 32,
                'emp_id' => 'CN031',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'นพมาศ',
                'emp_lastname' => 'ฐานะจิตต์',
                'emp_nickname' => 'Nop',
                'emp_email' => 'nop.compliance@company.com',
                'emp_phone' => '0892345679',
                'emp_department_id' => 21,
                'emp_team_id' => 45,
                'emp_position_id' => 83,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],

            // ===================== ADDITIONAL STAFF =====================
            [
                'id' => 33,
                'emp_id' => 'CN032',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'สำเร็จ',
                'emp_lastname' => 'กิจการ',
                'emp_nickname' => 'Sam',
                'emp_email' => 'samrej.project@company.com',
                'emp_phone' => '0893456780',
                'emp_department_id' => 12,
                'emp_team_id' => 22,
                'emp_position_id' => 15,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 34,
                'emp_id' => 'CN033',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'สวนีย์',
                'emp_lastname' => 'กิมอุยส์',
                'emp_nickname' => 'Supanee',
                'emp_email' => 'suwanee.project@company.com',
                'emp_phone' => '0894567891',
                'emp_department_id' => 12,
                'emp_team_id' => 23,
                'emp_position_id' => 15,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 35,
                'emp_id' => 'CN034',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'วิชิต',
                'emp_lastname' => 'ของเหม',
                'emp_nickname' => 'Wit',
                'emp_email' => 'wichit.sms@company.com',
                'emp_phone' => '0895678902',
                'emp_department_id' => 11,
                'emp_team_id' => 20,
                'emp_position_id' => 28,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 36,
                'emp_id' => 'CN035',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'ศิริณ',
                'emp_lastname' => 'ปรีชา',
                'emp_nickname' => 'Sirin',
                'emp_email' => 'sirin.graphic@company.com',
                'emp_phone' => '0896789023',
                'emp_department_id' => 7,
                'emp_team_id' => 8,
                'emp_position_id' => 17,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 37,
                'emp_id' => 'CN036',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ธีรศักดิ์',
                'emp_lastname' => 'บัวไทย',
                'emp_nickname' => 'Teerasak',
                'emp_email' => 'teerasak.interactive@company.com',
                'emp_phone' => '0897890134',
                'emp_department_id' => 6,
                'emp_team_id' => 7,
                'emp_position_id' => 28,
                'emp_password' => Hash::make('Pass123456'),
                'emp_permission' => 'user',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
        ]);
    }
}
