<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        // ล้างข้อมูลเก่าก่อน ป้องกัน id ซ้ำ
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('ems_employees')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('ems_employees')->insert([
            [
                'id' => 1,
                'emp_id' => 'CN0000',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'แอดมิน',
                'emp_lastname' => 'แอดมิน',
                'emp_nickname' => 'Admin',
                'emp_email' => 'admin@admin.com',
                'emp_phone' => '1234567890',
                'emp_department_id' => 14,
                'emp_team_id' => 28,
                'emp_position_id' => 28,
                'emp_password' => Hash::make('Admin_Pass101'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => null,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 2,
                'emp_id' => 'CN0001',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'HR',
                'emp_lastname' => 'HR',
                'emp_nickname' => 'HR',
                'emp_email' => 'hr@hr.com',
                'emp_phone' => '1234567809',
                'emp_department_id' => 13,
                'emp_team_id' => 27,
                'emp_position_id' => 33,
                'emp_password' => Hash::make('HR_Pass909'),
                'emp_permission' => 'hr',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 3,
                'emp_id' => 'CN0101',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ณัฐพงศ์',
                'emp_lastname' => 'คงศิลป์',
                'emp_nickname' => 'โอม',
                'emp_email' => '66160100@go.buu.ac.th',
                'emp_phone' => '0811111111',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 24,
                'emp_password' => Hash::make('66160100'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 4,
                'emp_id' => 'CN0230',
                'emp_company_id' => 1,
                'emp_prefix' => 'นางสาว',
                'emp_firstname' => 'นิธิวดี',
                'emp_lastname' => 'บัวผัน',
                'emp_nickname' => 'แป้ง',
                'emp_email' => '66160230@go.buu.ac.th',
                'emp_phone' => '0822222222',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 25,
                'emp_password' => Hash::make('66160230'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 5,
                'emp_id' => 'CN0083',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ชิตดนัย',
                'emp_lastname' => 'รัตนเทียนทอง',
                'emp_nickname' => 'ปอนด์',
                'emp_email' => '66160083@go.buu.ac.th',
                'emp_phone' => '0833333333',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 29,
                'emp_password' => Hash::make('66160083'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 6,
                'emp_id' => 'CN0102',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ณัฐพงษ์',
                'emp_lastname' => 'คำมา',
                'emp_nickname' => 'ไอซ์',
                'emp_email' => '66160101@go.buu.ac.th',
                'emp_phone' => '0844444444',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 29,
                'emp_password' => Hash::make('66160101'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 7,
                'emp_id' => 'CN0081',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'กัจจาฤกษ์',
                'emp_lastname' => 'ศรีภิรมย์',
                'emp_nickname' => 'คิว',
                'emp_email' => '66160081@go.buu.ac.th',
                'emp_phone' => '0855555555',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 31,
                'emp_password' => Hash::make('66160081'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 8,
                'emp_id' => 'CN0350',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ณปรารินทร์',
                'emp_lastname' => 'เสียงดี',
                'emp_nickname' => 'ภีม',
                'emp_email' => '66160350@go.buu.ac.th',
                'emp_phone' => '0866666666',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 30,
                'emp_password' => Hash::make('66160350'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 9,
                'emp_id' => 'CN0103',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ธนูศิลป์',
                'emp_lastname' => 'ลีนาราช',
                'emp_nickname' => 'ซัน',
                'emp_email' => '66160102@go.buu.ac.th',
                'emp_phone' => '0877777777',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 32,
                'emp_password' => Hash::make('66160102'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 10,
                'emp_id' => 'CN0342',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'กิดากร',
                'emp_lastname' => 'รัตนหิรัญ',
                'emp_nickname' => 'เป้ย',
                'emp_email' => '66160342@go.buu.ac.th',
                'emp_phone' => '0888888888',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 32,
                'emp_password' => Hash::make('66160342'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 11,
                'emp_id' => 'CN0370',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'รวีโรจน์',
                'emp_lastname' => 'สนธิ',
                'emp_nickname' => 'มอส',
                'emp_email' => '66160370@go.buu.ac.th',
                'emp_phone' => '0899999999',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 28,
                'emp_password' => Hash::make('66160370'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 12,
                'emp_id' => 'CN0106',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'ศุภณัฐ',
                'emp_lastname' => 'พันโกฏิ',
                'emp_nickname' => 'เอิร์ธ',
                'emp_email' => '66160106@go.buu.ac.th',
                'emp_phone' => '0900000000',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 26,
                'emp_password' => Hash::make('66160106'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
            [
                'id' => 13,
                'emp_id' => 'CN0088',
                'emp_company_id' => 1,
                'emp_prefix' => 'นาย',
                'emp_firstname' => 'โยธิน',
                'emp_lastname' => 'สีใสธรรม',
                'emp_nickname' => 'โย',
                'emp_email' => '66160088@go.buu.ac.th',
                'emp_phone' => '0911111111',
                'emp_department_id' => 15,
                'emp_team_id' => 29,
                'emp_position_id' => 28,
                'emp_password' => Hash::make('66160088'),
                'emp_permission' => 'admin',
                'emp_created_at' => now(),
                'emp_create_by' => 1,
                'emp_delete_status' => 'active',
            ],
        ]);
    }
}
