<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventsSeeder extends Seeder
{
    public function run(): void
    {
        // ลบของเก่า + รีเซ็ต auto increment
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('ems_event')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // กำหนดเวลาเริ่มต้นสำหรับกิจกรรมต่างๆ
        $now = '09:00:00';

        DB::table('ems_event')->insert([
            // ==================================================
            // DONE
            // ==================================================
            [
                'id' => 1,
                'evn_title' => 'ประชุมสรุปผลโครงการ',
                'evn_category_id' => 1,
                'evn_description' => 'สรุปผลการดำเนินงานและปัญหาที่พบ',
                'evn_date' => '2026-02-07',
                'evn_timestart' => '09:00:00',
                'evn_timeend' => '10:30:00',
                'evn_duration' => 90,
                'evn_location' => 'ห้องประชุม A',
                'evn_file' => 'not_have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'done',
            ],
            [
                'id' => 2,
                'evn_title' => 'สัมนาความปลอดภัยไซเบอร์',
                'evn_category_id' => 2,
                'evn_description' => 'ให้ความรู้เรื่องภัยคุกคามไซเบอร์และการป้องกันข้อมูล',
                'evn_date' => '2026-02-09',
                'evn_timestart' => '13:00:00',
                'evn_timeend' => '15:30:00',
                'evn_duration' => 150,
                'evn_location' => 'อาคาร IF ห้อง 4T04',
                'evn_file' => 'have',
                'evn_create_by' => 2,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'done',
            ],
            [
                'id' => 3,
                'evn_title' => 'อบรมการใช้งานระบบ EMS',
                'evn_category_id' => 3,
                'evn_description' => 'อบรมพนักงานใหม่เกี่ยวกับระบบ Eventra Management System',
                'evn_date' => '2026-02-11',
                'evn_timestart' => '09:00:00',
                'evn_timeend' => '12:00:00',
                'evn_duration' => 180,
                'evn_location' => 'ห้องคอมพิวเตอร์ 2',
                'evn_file' => 'have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'done',
            ],
            [
                'id' => 4,
                'evn_title' => 'กิจกรรมเดิน-วิ่งการกุศล',
                'evn_category_id' => 4,
                'evn_description' => 'กิจกรรมเพื่อสุขภาพและระดมทุนช่วยเหลือผู้ด้อยโอกาส',
                'evn_date' => '2026-02-12',
                'evn_timestart' => '06:00:00',
                'evn_timeend' => '09:00:00',
                'evn_duration' => 180,
                'evn_location' => 'บางแสน ชลบุรี',
                'evn_file' => 'not_have',
                'evn_create_by' => 3,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'done',
            ],

            // ==================================================
            // ONGOING
            // ==================================================
            [
                'id' => 5,
                'evn_title' => 'นำเสนอ Demo',
                'evn_category_id' => 4,
                'evn_description' => 'นำเสนอ Demo Cycle 3',
                'evn_date' => '2026-03-10',
                'evn_timestart' => '10:00:00',
                'evn_timeend' => '12:00:00',
                'evn_duration' => 120,
                'evn_location' => 'ตึก IF-6T05',
                'evn_file' => 'have',
                'evn_create_by' => 2,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'ongoing',
            ],
            [
                'id' => 6,
                'evn_title' => 'ประชุมติดตามความคืบหน้าโปรเจค',
                'evn_category_id' => 1,
                'evn_description' => 'ติดตาม progress งานและแก้ปัญหาที่เจอระหว่างพัฒนา',
                'evn_date' => '2026-03-11',
                'evn_timestart' => '13:00:00',
                'evn_timeend' => '14:00:00',
                'evn_duration' => 60,
                'evn_location' => 'ห้องประชุม B',
                'evn_file' => 'not_have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'ongoing',
            ],
            [
                'id' => 13,
                'evn_title' => 'ทำงาน Sprint Development',
                'evn_category_id' => 3,
                'evn_description' => 'งาน Development ของ Sprint ปัจจุบัน',
                'evn_date' => '2026-03-12',
                'evn_timestart' => '08:00:00',
                'evn_timeend' => '17:00:00',
                'evn_duration' => 540,
                'evn_location' => 'สำนักงาน',
                'evn_file' => 'not_have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'ongoing',
            ],
            [
                'id' => 17,
                'evn_title' => 'Review Code & Testing',
                'evn_category_id' => 3,
                'evn_description' => 'ตรวจสอบโค้ดและทำการทดสอบ',
                'evn_date' => date('Y-m-d', strtotime('+0 day')),
                'evn_timestart' => date('H:i:s', strtotime($now . ' +0 hours')),
                'evn_timeend' => date('H:i:s', strtotime($now . ' +4 hours')),
                'evn_duration' => 120,
                'evn_location' => 'สำนักงาน',
                'evn_file' => 'not_have',
                'evn_create_by' => 2,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'ongoing',
            ],

            // ==================================================
            // UPCOMING
            // ==================================================
            [
                'id' => 7,
                'evn_title' => 'ประชุมทีม',
                'evn_category_id' => 1,
                'evn_description' => 'ประชุมทีมครั้งที่ 25',
                'evn_date' => date('Y-m-d', strtotime('+5 day')),
                'evn_timestart' => $now,
                'evn_timeend' => date('H:i:s', strtotime($now . ' +2 hours')),
                'evn_duration' => 120,
                'evn_location' => 'ห้องประชุม CN154',
                'evn_file' => 'not_have',
                'evn_create_by' => 3,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'id' => 8,
                'evn_title' => 'อบรมการทดสอบซอฟต์แวร์ (QA)',
                'evn_category_id' => 3,
                'evn_description' => 'อบรมพื้นฐานการทำ Test case, Bug report และการใช้งานเครื่องมือ QA',
                'evn_date' => date('Y-m-d', strtotime('+6 day')),
                'evn_timestart' => $now,
                'evn_timeend' => date('H:i:s', strtotime($now . ' +3 hours')),
                'evn_duration' => 180,
                'evn_location' => 'ห้องอบรม 101',
                'evn_file' => 'have',
                'evn_create_by' => 2,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'id' => 9,
                'evn_title' => 'สัมนาแนวโน้มเทคโนโลยีปี 2026',
                'evn_category_id' => 2,
                'evn_description' => 'อัปเดตเทคโนโลยีและนวัตกรรมที่กำลังมาแรงในปี 2026',
                'evn_date' => date('Y-m-d', strtotime('+7 day')),
                'evn_timestart' => date('H:i:s', strtotime($now . ' +4.5 hours')),
                'evn_timeend' => date('H:i:s', strtotime($now . ' +6.5 hours')),
                'evn_duration' => 150,
                'evn_location' => 'ห้องสัมมนาใหญ่ อาคารนวัตกรรม',
                'evn_file' => 'have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'id' => 10,
                'evn_title' => 'กิจกรรมปลูกต้นไม้วันสิ่งแวดล้อม',
                'evn_category_id' => 4,
                'evn_description' => 'ร่วมกันปลูกต้นไม้เพิ่มพื้นที่สีเขียวและสร้างจิตสำนึกด้านสิ่งแวดล้อม',
                'evn_date' => date('Y-m-d', strtotime('+9 day')),
                'evn_timestart' => date('H:i:s', strtotime($now . ' -1.5 hours')),
                'evn_timeend' => date('H:i:s', strtotime($now . ' +1.5 hours')),
                'evn_duration' => 180,
                'evn_location' => 'สวนสาธารณะบางแสน',
                'evn_file' => 'not_have',
                'evn_create_by' => 4,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'id' => 11,
                'evn_title' => 'Workshop การออกแบบ UI/UX',
                'evn_category_id' => 3,
                'evn_description' => 'เวิร์กช็อปออกแบบ UI/UX เบื้องต้น พร้อมทำ prototype',
                'evn_date' => date('Y-m-d', strtotime('+10 day')),
                'evn_timestart' => $now,
                'evn_timeend' => date('H:i:s', strtotime($now . ' +5 hours')),
                'evn_duration' => 300,
                'evn_location' => 'ห้องคอมพิวเตอร์ 3',
                'evn_file' => 'have',
                'evn_create_by' => 2,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'id' => 12,
                'evn_title' => 'ประชุมคณะกรรมการบริหาร',
                'evn_category_id' => 1,
                'evn_description' => 'ประชุมสรุปผลการดำเนินงานและแผนงานไตรมาสถัดไป',
                'evn_date' => date('Y-m-d', strtotime('+11 day')),
                'evn_timestart' => date('H:i:s', strtotime($now . ' +5 hours')),
                'evn_timeend' => date('H:i:s', strtotime($now . ' +7 hours')),
                'evn_duration' => 120,
                'evn_location' => 'ห้องประชุมใหญ่ ชั้น 5',
                'evn_file' => 'not_have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'id' => 14,
                'evn_title' => 'อบรมการสื่อสารประสิทธิภาพ',
                'evn_category_id' => 3,
                'evn_description' => 'อบรมทักษะการสื่อสาร นำเสนอ และการทำงานเป็นทีม',
                'evn_date' => date('Y-m-d', strtotime('+12 day')),
                'evn_timestart' => $now,
                'evn_timeend' => date('H:i:s', strtotime($now . ' +2.5 hours')),
                'evn_duration' => 150,
                'evn_location' => 'ห้องสัมมนา 1',
                'evn_file' => 'have',
                'evn_create_by' => 3,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'id' => 15,
                'evn_title' => 'ประชุมประเมินผลโปรเจคครึ่งปี',
                'evn_category_id' => 1,
                'evn_description' => 'ประเมินผล ต้นทุน และ schedule ของโปรเจค',
                'evn_date' => date('Y-m-d', strtotime('+14 day')),
                'evn_timestart' => $now,
                'evn_timeend' => date('H:i:s', strtotime($now . ' +2.5 hours')),
                'evn_duration' => 150,
                'evn_location' => 'ห้องประชุมใหญ่ ชั้น 5',
                'evn_file' => 'not_have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'id' => 16,
                'evn_title' => 'กิจกรรมแลกเปลี่ยนประสบการณ์',
                'evn_category_id' => 4,
                'evn_description' => 'กิจกรรมแลกเปลี่ยนประสบการณ์การทำงานจากหลายแผนก',
                'evn_date' => date('Y-m-d', strtotime('+16 day')),
                'evn_timestart' => date('H:i:s', strtotime($now . ' +5 hours')),
                'evn_timeend' => date('H:i:s', strtotime($now . ' +7 hours')),
                'evn_duration' => 120,
                'evn_location' => 'ห้องสัมมนา 2',
                'evn_file' => 'have',
                'evn_create_by' => 4,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],

        ]);
    }
}
