<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EventsSeeder extends Seeder{
    public function run(): void{
        DB::table('ems_event')->insert([
            [
                'evn_title' => 'ประชุมวางแผนงานประจำปี',
                'evn_category_id' => 1,
                'evn_description' => 'ประชุมทีมงานเพื่อวางแผนกิจกรรมตลอดปี',
                'evn_date' => '2025-10-25',
                'evn_timestart' => '09:00:00',
                'evn_timeend' => '11:00:00',
                'evn_duration' => 120,
                'evn_location' => 'ห้องประชุม CN154',
                'evn_file' => 'not_have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'done',
            ],
            [
                'evn_title' => 'อบรมการใช้งานระบบ Eventra',
                'evn_category_id' => 3,
                'evn_description' => 'อบรมการใช้งานระบบ EMS ให้กับพนักงานใหม่',
                'evn_date' => '2025-10-28',
                'evn_timestart' => '13:00:00',
                'evn_timeend' => '16:00:00',
                'evn_duration' => 180,
                'evn_location' => 'ห้องคอมพิวเตอร์ 2',
                'evn_file' => 'have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'evn_title' => 'สัมนาความปลอดภัยไซเบอร์',
                'evn_category_id' => 2,
                'evn_description' => 'สัมนาให้ความรู้เกี่ยวกับการรักษาความปลอดภัยของข้อมูล',
                'evn_date' => '2025-11-02',
                'evn_timestart' => '09:30:00',
                'evn_timeend' => '12:00:00',
                'evn_duration' => 150,
                'evn_location' => 'อาคาร IF ห้อง 4T04',
                'evn_file' => 'not_have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'ongoing',
            ],
            [
                'evn_title' => 'เวิร์กช็อปการออกแบบกราฟิก',
                'evn_category_id' => 3,
                'evn_description' => 'อบรมการใช้งาน Adobe Photoshop และ Illustrator เบื้องต้น',
                'evn_date' => '2025-11-05',
                'evn_timestart' => '10:00:00',
                'evn_timeend' => '15:00:00',
                'evn_duration' => 300,
                'evn_location' => 'ห้องเรียน 203 อาคารศิลปกรรม',
                'evn_file' => 'have',
                'evn_create_by' => 2,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'evn_title' => 'กิจกรรมเดิน-วิ่งการกุศล',
                'evn_category_id' => 4,
                'evn_description' => 'ร่วมกันออกกำลังกายและระดมทุนเพื่อช่วยเหลือผู้ด้อยโอกาส',
                'evn_date' => '2025-11-08',
                'evn_timestart' => '06:00:00',
                'evn_timeend' => '09:00:00',
                'evn_duration' => 180,
                'evn_location' => 'บางแสน ชลบุรี',
                'evn_file' => 'not_have',
                'evn_create_by' => 3,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'ongoing',
            ],
            [
                'evn_title' => 'ประชุมคณะกรรมการบริหาร',
                'evn_category_id' => 1,
                'evn_description' => 'ประชุมสรุปผลการดำเนินงานไตรมาส 3',
                'evn_date' => '2025-11-10',
                'evn_timestart' => '14:00:00',
                'evn_timeend' => '16:00:00',
                'evn_duration' => 120,
                'evn_location' => 'ห้องประชุมใหญ่ ชั้น 5',
                'evn_file' => 'not_have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'ongoing',
            ],
            [
                'evn_title' => 'อบรมความปลอดภัยในการทำงาน',
                'evn_category_id' => 2,
                'evn_description' => 'อบรมให้ความรู้เรื่องความปลอดภัยในโรงงาน',
                'evn_date' => '2025-11-12',
                'evn_timestart' => '08:30:00',
                'evn_timeend' => '12:00:00',
                'evn_duration' => 210,
                'evn_location' => 'ห้องอบรม 1',
                'evn_file' => 'have',
                'evn_create_by' => 2,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'evn_title' => 'สัมนาการพัฒนาทักษะผู้นำ',
                'evn_category_id' => 3,
                'evn_description' => 'สัมนาเสริมทักษะการเป็นผู้นำสำหรับหัวหน้างาน',
                'evn_date' => '2025-11-15',
                'evn_timestart' => '09:00:00',
                'evn_timeend' => '17:00:00',
                'evn_duration' => 480,
                'evn_location' => 'โรงแรมเซ็นทาราพัทยา',
                'evn_file' => 'have',
                'evn_create_by' => 3,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'done',
            ],
            [
                'evn_title' => 'กิจกรรมปลูกต้นไม้วันสิ่งแวดล้อม',
                'evn_category_id' => 4,
                'evn_description' => 'ร่วมกันปลูกต้นไม้เพิ่มพื้นที่สีเขียว',
                'evn_date' => '2025-11-20',
                'evn_timestart' => '07:30:00',
                'evn_timeend' => '10:30:00',
                'evn_duration' => 180,
                'evn_location' => 'สถานตากอากาศบางปู',
                'evn_file' => 'not_have',
                'evn_create_by' => 4,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'evn_title' => 'ประชุมเตรียมงานปีใหม่',
                'evn_category_id' => 1,
                'evn_description' => 'เตรียมความพร้อมสำหรับกิจกรรมปีใหม่ขององค์กร',
                'evn_date' => '2025-11-25',
                'evn_timestart' => '10:00:00',
                'evn_timeend' => '12:00:00',
                'evn_duration' => 120,
                'evn_location' => 'ห้องประชุม B',
                'evn_file' => 'not_have',
                'evn_create_by' => 2,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'ongoing',
            ],
            [
                'evn_title' => 'กิจกรรม CSR เยี่ยมบ้านเด็กกำพร้า',
                'evn_category_id' => 4,
                'evn_description' => 'ร่วมบริจาคสิ่งของและจัดกิจกรรมสันทนาการให้เด็กกำพร้า',
                'evn_date' => '2025-11-28',
                'evn_timestart' => '08:00:00',
                'evn_timeend' => '14:00:00',
                'evn_duration' => 360,
                'evn_location' => 'มูลนิธิบ้านเด็กยิ้ม',
                'evn_file' => 'have',
                'evn_create_by' => 3,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'done',
            ],
            [
                'evn_title' => 'สัมนาแนวโน้มเทคโนโลยีปี 2026',
                'evn_category_id' => 2,
                'evn_description' => 'อัปเดตเทคโนโลยีและนวัตกรรมที่จะมาในปี 2026',
                'evn_date' => '2025-12-01',
                'evn_timestart' => '09:30:00',
                'evn_timeend' => '12:00:00',
                'evn_duration' => 150,
                'evn_location' => 'ห้องสัมมนาใหญ่ อาคารนวัตกรรม',
                'evn_file' => 'have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'evn_title' => 'การประชุมทีมพัฒนาเว็บไซต์',
                'evn_category_id' => 1,
                'evn_description' => 'ประชุมปรับปรุงฟีเจอร์ใหม่ของเว็บไซต์บริษัท',
                'evn_date' => '2025-12-03',
                'evn_timestart' => '13:00:00',
                'evn_timeend' => '15:30:00',
                'evn_duration' => 150,
                'evn_location' => 'ห้อง Developer Lab',
                'evn_file' => 'not_have',
                'evn_create_by' => 4,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
            [
                'evn_title' => 'อบรมการจัดการโครงการ',
                'evn_category_id' => 3,
                'evn_description' => 'เรียนรู้เทคนิคการวางแผนและควบคุมโครงการอย่างมืออาชีพ',
                'evn_date' => '2025-12-06',
                'evn_timestart' => '09:00:00',
                'evn_timeend' => '16:00:00',
                'evn_duration' => 420,
                'evn_location' => 'ห้องอบรม 101',
                'evn_file' => 'have',
                'evn_create_by' => 2,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'done',
            ],
            [
                'evn_title' => 'งานเลี้ยงส่งท้ายปีเก่า',
                'evn_category_id' => 4,
                'evn_description' => 'กิจกรรมสังสรรค์และมอบของรางวัลให้พนักงาน',
                'evn_date' => '2025-12-30',
                'evn_timestart' => '18:00:00',
                'evn_timeend' => '22:00:00',
                'evn_duration' => 240,
                'evn_location' => 'ลานกิจกรรมกลางแจ้ง',
                'evn_file' => 'have',
                'evn_create_by' => 1,
                'evn_created_at' => now(),
                'evn_deleted_at' => null,
                'evn_deleted_by' => null,
                'evn_status' => 'upcoming',
            ],
        ]);
    }
}
